export const VOICE_OPTIONS = [
    { value: 'bn-BD-NabanitaNeural', label: 'Nabanita', group: 'Bangla (Bangladesh)', accent: 'BD', gender: 'Female', flag: '🇧🇩', audio: '' },
    { value: 'bn-BD-PradeepNeural', label: 'Pradeep', group: 'Bangla (Bangladesh)', accent: 'BD', gender: 'Male', flag: '🇧🇩', audio: '' },
    { value: 'bn-IN-TanishaaNeural', label: 'Tanishaa', group: 'Bengali (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'bn-IN-BashkarNeural', label: 'Bashkar', group: 'Bengali (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'de-DE-FlorianMultilingualNeural', label: 'Florian', group: 'German (Germany)', accent: 'DE', gender: 'Male', flag: '🇩🇪', audio: 'de-DE-FlorianMultilingual-General-Audio-wav.wav' },
    { value: 'de-DE-Florian:DragonHDLatestNeural', label: 'Florian', group: 'German (Germany)', accent: 'DE', gender: 'Male', flag: '🇩🇪', audio: 'de-DE-FlorianDragonHDLatest-General-Audio-wav.wav' },
    { value: 'de-DE-Seraphina:DragonHDLatestNeural', label: 'Seraphina', group: 'German (Germany)', accent: 'DE', gender: 'Female', flag: '🇩🇪', audio: 'de-DE-SeraphinaDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-GB-AdaMultilingualNeural', label: 'Ada', group: 'English (United Kingdom)', accent: 'GB', gender: 'Female', flag: '🇬🇧', audio: 'en-GB-AdaMultilingual-General-Audio-wav.wav' },
    { value: 'en-GB-OllieMultilingualNeural', label: 'Ollie', group: 'English (United Kingdom)', accent: 'GB', gender: 'Male', flag: '🇬🇧', audio: 'en-GB-OllieMultilingual-General-Audio-wav.wav' },
    { value: 'en-IN-AaravNeural', label: 'Aarav', group: 'English (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: 'en-IN-Aarav-General-Audio-wav.wav' },
    { value: 'en-IN-AashiNeural', label: 'Aashi', group: 'English (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: 'en-IN-Aashi-General-Audio-wav.wav' },
    { value: 'en-IN-AartiNeural', label: 'Aarti', group: 'English (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: 'en-IN-Aarti-General-Audio-wav.wav' },
    { value: 'en-IN-ArjunNeural', label: 'Arjun', group: 'English (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: 'en-IN-Arjun-General-Audio-wav.wav' },
    { value: 'en-IN-AnanyaNeural', label: 'Ananya', group: 'English (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: 'en-IN-Ananya-General-Audio-wav.wav' },
    { value: 'en-IN-KavyaNeural', label: 'Kavya', group: 'English (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: 'en-IN-Kavya-General-Audio-wav.wav' },
    { value: 'en-IN-KunalNeural', label: 'Kunal', group: 'English (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: 'en-IN-Kunal-General-Audio-wav.wav' },
    { value: 'en-IN-NeerjaNeural', label: 'Neerja', group: 'English (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: 'en-IN-Neerja-General-Audio-wav.wav' },
    { value: 'en-IN-PrabhatNeural', label: 'Prabhat', group: 'English (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: 'en-IN-Prabhat-General-Audio-wav.wav' },
    { value: 'en-IN-RehaanNeural', label: 'Rehaan', group: 'English (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: 'en-IN-Rehaan-General-Audio-wav.wav' },
    { value: 'en-IN-AartiIndicNeural', label: 'AartiIndic', group: 'English (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'en-IN-ArjunIndicNeural', label: 'ArjunIndic', group: 'English (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'en-IN-NeerjaIndicNeural', label: 'NeerjaIndic', group: 'English (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'en-IN-PrabhatIndicNeural', label: 'PrabhatIndic', group: 'English (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'en-KE-AsiliaNeural', label: 'Asilia', group: 'English (Kenya)', accent: 'KE', gender: 'Female', flag: '🇰🇪', audio: '' },
    { value: 'en-KE-ChilembaNeural', label: 'Chilemba', group: 'English (Kenya)', accent: 'KE', gender: 'Male', flag: '🇰🇪', audio: '' },
    { value: 'en-NG-EzinneNeural', label: 'Ezinne', group: 'English (Nigeria)', accent: 'NG', gender: 'Female', flag: '🇳🇬', audio: '' },
    { value: 'en-NG-AbeoNeural', label: 'Abeo', group: 'English (Nigeria)', accent: 'NG', gender: 'Male', flag: '🇳🇬', audio: '' },
    { value: 'en-NZ-MollyNeural', label: 'Molly', group: 'English (New Zealand)', accent: 'NZ', gender: 'Female', flag: '🇳🇿', audio: '' },
    { value: 'en-NZ-MitchellNeural', label: 'Mitchell', group: 'English (New Zealand)', accent: 'NZ', gender: 'Male', flag: '🇳🇿', audio: '' },
    { value: 'en-PH-RosaNeural', label: 'Rosa', group: 'English (Philippines)', accent: 'PH', gender: 'Female', flag: '🇵🇭', audio: '' },
    { value: 'en-PH-JamesNeural', label: 'James', group: 'English (Philippines)', accent: 'PH', gender: 'Male', flag: '🇵🇭', audio: '' },
    { value: 'en-SG-LunaNeural', label: 'Luna', group: 'English (Singapore)', accent: 'SG', gender: 'Female', flag: '🇸🇬', audio: '' },
    { value: 'en-SG-WayneNeural', label: 'Wayne', group: 'English (Singapore)', accent: 'SG', gender: 'Male', flag: '🇸🇬', audio: '' },
    { value: 'en-TZ-ImaniNeural', label: 'Imani', group: 'English (Tanzania)', accent: 'TZ', gender: 'Female', flag: '🇹🇿', audio: '' },
    { value: 'en-TZ-ElimuNeural', label: 'Elimu', group: 'English (Tanzania)', accent: 'TZ', gender: 'Male', flag: '🇹🇿', audio: '' },
    { value: 'en-US-AvaMultilingualNeural', label: 'Ava', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-AvaMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-AndrewMultilingualNeural', label: 'Andrew', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-AndrewMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-EmmaMultilingualNeural', label: 'Emma', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-EmmaMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-AlloyTurboMultilingualNeural', label: 'Alloy', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-AlloyTurboMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-EchoTurboMultilingualNeural', label: 'Echo', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-EchoTurboMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-FableTurboMultilingualNeural', label: 'Fable', group: 'English (United States)', accent: 'US', gender: 'Neutral', flag: '🇺🇸', audio: 'en-US-FableTurboMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-OnyxTurboMultilingualNeural', label: 'Onyx', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-OnyxTurboMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-NovaTurboMultilingualNeural', label: 'Nova', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-NovaTurboMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-ShimmerTurboMultilingualNeural', label: 'Shimmer', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-ShimmerTurboMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-BrianMultilingualNeural', label: 'Brian', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-BrianMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-AvaNeural', label: 'Ava', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Ava-General-Audio-wav.wav' },
    { value: 'en-US-AndrewNeural', label: 'Andrew', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Andrew-General-Audio-wav.wav' },
    { value: 'en-US-EmmaNeural', label: 'Emma', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Emma-General-Audio-wav.wav' },
    { value: 'en-US-BrianNeural', label: 'Brian', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Brian-General-Audio-wav.wav' },
    { value: 'en-US-JennyNeural', label: 'Jenny', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Jenny-General-audio-wav.wav' },
    { value: 'en-US-GuyNeural', label: 'Guy', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Guy-General-audio-wav.wav' },
    { value: 'en-US-AriaNeural', label: 'Aria', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Aria-General-audio-wav.wav' },
    { value: 'en-US-DavisNeural', label: 'Davis', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'En-US-Davis-General-Audio-wav.wav' },
    { value: 'en-US-JaneNeural', label: 'Jane', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'En-US-Jane-General-Audio-wav.wav' },
    { value: 'en-US-JasonNeural', label: 'Jason', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'En-US-Jason-General-Audio-wav.wav' },
    { value: 'en-US-KaiNeural', label: 'Kai', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Kai-General-Audio-wav.wav' },
    { value: 'en-US-LunaNeural', label: 'Luna', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Luna-General-Audio-wav.wav' },
    { value: 'en-US-SaraNeural', label: 'Sara', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Sara-General-Audio-wav.wav' },
    { value: 'en-US-TonyNeural', label: 'Tony', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'En-US-Tony-General-Audio-wav.wav' },
    { value: 'en-US-NancyNeural', label: 'Nancy', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'En-US-Nancy-General-Audio-wav.wav' },
    { value: 'en-US-CoraMultilingualNeural', label: 'Cora', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-CoraMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-ChristopherMultilingualNeural', label: 'Christopher', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-ChristopherMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-BrandonMultilingualNeural', label: 'Brandon', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-BrandonMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-AmberNeural', label: 'Amber', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Amber-General-Audio-wav.wav' },
    { value: 'en-US-AnaNeural', label: 'Ana', group: 'English (United States)', accent: 'US', gender: 'Female, Child', flag: '🇺🇸', audio: 'en-US-Ana-General-Audio-wav.wav' },
    { value: 'en-US-AshleyNeural', label: 'Ashley', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Ashley-General-Audio-wav.wav' },
    { value: 'en-US-BrandonNeural', label: 'Brandon', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Brandon-General-Audio-wav.wav' },
    { value: 'en-US-ChristopherNeural', label: 'Christopher', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Christopher-General-Audio-wav.wav' },
    { value: 'en-US-CoraNeural', label: 'Cora', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Cora-General-Audio-wav.wav' },
    { value: 'en-US-ElizabethNeural', label: 'Elizabeth', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Elizabeth-General-Audio-wav.wav' },
    { value: 'en-US-EricNeural', label: 'Eric', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Eric-General-Audio-wav.wav' },
    { value: 'en-US-JacobNeural', label: 'Jacob', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Jacob-General-Audio-wav.wav' },
    { value: 'en-US-JennyMultilingualNeural', label: 'Jenny', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-JennyMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-MichelleNeural', label: 'Michelle', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Michelle-General-Audio-wav.wav' },
    { value: 'en-US-MonicaNeural', label: 'Monica', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Monica-General-Audio-wav.wav' },
    { value: 'en-US-RogerNeural', label: 'Roger', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Roger-General-Audio-wav.wav' },
    { value: 'en-US-RyanMultilingualNeural', label: 'Ryan', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-RyanMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-SteffanNeural', label: 'Steffan', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Steffan-General-Audio-wav.wav' },
    { value: 'en-US-AdamMultilingualNeural', label: 'Adam', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: '' },
    { value: 'en-US-AIGenerate1Neural', label: 'AIGenerate1', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: '' },
    { value: 'en-US-AIGenerate2Neural', label: 'AIGenerate2', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: '' },
    { value: 'en-US-AmandaMultilingualNeural', label: 'Amanda', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: '' },
    { value: 'en-US-AshTurboMultilingualNeural', label: 'Ash', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: '' },
    { value: 'en-US-BlueNeural', label: 'Blue', group: 'English (United States)', accent: 'US', gender: 'Neutral', flag: '🇺🇸', audio: '' },
    { value: 'en-US-DavisMultilingualNeural', label: 'Davis', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: '' },
    { value: 'en-US-DerekMultilingualNeural', label: 'Derek', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: '' },
    { value: 'en-US-DustinMultilingualNeural', label: 'Dustin', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: '' },
    { value: 'en-US-EvelynMultilingualNeural', label: 'Evelyn', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: '' },
    { value: 'en-US-LewisMultilingualNeural', label: 'Lewis', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: '' },
    { value: 'en-US-LolaMultilingualNeural', label: 'Lola', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: '' },
    { value: 'en-US-NancyMultilingualNeural', label: 'Nancy', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: '' },
    { value: 'en-US-PhoebeMultilingualNeural', label: 'Phoebe', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: '' },
    { value: 'en-US-SamuelMultilingualNeural', label: 'Samuel', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: '' },
    { value: 'en-US-SerenaMultilingualNeural', label: 'Serena', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: '' },
    { value: 'en-US-SteffanMultilingualNeural', label: 'Steffan', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-SteffanMultilingual-General-Audio-wav.wav' },
    { value: 'en-US-Adam:DragonHDLatestNeural', label: 'Adam', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-AdamDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Andrew:DragonHDLatestNeural', label: 'Andrew', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-AndrewDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Andrew2:DragonHDLatestNeural', label: 'Andrew2', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Andrew2DragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Ava:DragonHDLatestNeural', label: 'Ava', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-AvaDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Brian:DragonHDLatestNeural', label: 'Brian', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-BrianDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Davis:DragonHDLatestNeural', label: 'Davis', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-DavisDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Emma:DragonHDLatestNeural', label: 'Emma', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-EmmaDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Emma2:DragonHDLatestNeural', label: 'Emma2', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Emma2DragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Steffan:DragonHDLatestNeural', label: 'Steffan', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-SteffanDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Alloy:DragonHDLatestNeural', label: 'Alloy', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-AlloyDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Andrew3:DragonHDLatestNeural', label: 'Andrew3', group: 'English (United States)', accent: 'US', gender: 'Male', flag: '🇺🇸', audio: 'en-US-Andrew3DragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Aria:DragonHDLatestNeural', label: 'Aria', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-AriaDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Ava3:DragonHDLatestNeural', label: 'Ava3', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-Ava3DragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Bree:DragonHDLatestNeural', label: 'Bree', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-BreeDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Jenny:DragonHDLatestNeural', label: 'Jenny', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-JennyDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-MultiTalker-Ava-Andrew:DragonHDLatestNeural', label: 'MultiTalker-Ava-Andrew', group: 'English (United States)', accent: 'US', gender: 'Neutral', flag: '🇺🇸', audio: 'en-US-MultiTalker-Ava-Andrew-Audio-wav.wav' },
    { value: 'en-US-MultiTalker-Ava-Steffan:DragonHDLatestNeural', label: 'MultiTalker-Ava-Steffan', group: 'English (United States)', accent: 'US', gender: 'Neutral', flag: '🇺🇸', audio: 'en-US-MultiTalker-Ava-Steffan-Audio-wav.wav' },
    { value: 'en-US-Nova:DragonHDLatestNeural', label: 'Nova', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-NovaDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Phoebe:DragonHDLatestNeural', label: 'Phoebe', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-PhoebeDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-US-Serena:DragonHDLatestNeural', label: 'Serena', group: 'English (United States)', accent: 'US', gender: 'Female', flag: '🇺🇸', audio: 'en-US-SerenaDragonHDLatest-General-Audio-wav.wav' },
    { value: 'en-ZA-LeahNeural', label: 'Leah', group: 'English (South Africa)', accent: 'ZA', gender: 'Female', flag: '🇿🇦', audio: '' },
    { value: 'en-ZA-LukeNeural', label: 'Luke', group: 'English (South Africa)', accent: 'ZA', gender: 'Male', flag: '🇿🇦', audio: '' },
    { value: 'es-ES-ArabellaMultilingualNeural', label: 'Arabella', group: 'Spanish (Spain)', accent: 'ES', gender: 'Female', flag: '🇪🇸', audio: 'es-ES-ArabellaMultilingual-General-Audio-wav.wav' },
    { value: 'es-ES-IsidoraMultilingualNeural', label: 'Isidora', group: 'Spanish (Spain)', accent: 'ES', gender: 'Female', flag: '🇪🇸', audio: 'es-ES-IsidoraMultilingual-General-Audio-wav.wav' },
    { value: 'es-ES-TristanMultilingualNeural', label: 'Tristan', group: 'Spanish (Spain)', accent: 'ES', gender: 'Male', flag: '🇪🇸', audio: 'es-ES-TristanMultilingual-General-Audio-wav.wav' },
    { value: 'es-ES-XimenaMultilingualNeural', label: 'Ximena', group: 'Spanish (Spain)', accent: 'ES', gender: 'Female', flag: '🇪🇸', audio: 'es-ES-XimenaMultilingual-General-Audio-wav.wav' },
    { value: 'es-ES-Tristan:DragonHDLatestNeural', label: 'Tristan', group: 'Spanish (Spain)', accent: 'ES', gender: 'Male', flag: '🇪🇸', audio: 'es-ES-TristanDragonHDLatest-General-Audio-wav.wav' },
    { value: 'es-ES-Ximena:DragonHDLatestNeural', label: 'Ximena', group: 'Spanish (Spain)', accent: 'ES', gender: 'Female', flag: '🇪🇸', audio: 'es-ES-XimenaDragonHDLatest-General-Audio-wav.wav' },
    { value: 'fr-FR-VivienneMultilingualNeural', label: 'Vivienne', group: 'French (France)', accent: 'FR', gender: 'Female', flag: '🇫🇷', audio: 'fr-FR-VivienneMultilingual-General-Audio-wav.wav' },
    { value: 'fr-FR-RemyMultilingualNeural', label: 'Remy', group: 'French (France)', accent: 'FR', gender: 'Male', flag: '🇫🇷', audio: 'fr-FR-RemyMultilingual-General-Audio-wav.wav' },
    { value: 'fr-FR-LucienMultilingualNeural', label: 'Lucien', group: 'French (France)', accent: 'FR', gender: 'Male', flag: '🇫🇷', audio: 'fr-FR-LucienMultilingual-General-Audio-wav.wav' },
    { value: 'fr-FR-Remy:DragonHDLatestNeural', label: 'Remy', group: 'French (France)', accent: 'FR', gender: 'Male', flag: '🇫🇷', audio: 'fr-FR-RemyDragonHDLatest-General-Audio-wav.wav' },
    { value: 'fr-FR-Vivienne:DragonHDLatestNeural', label: 'Vivienne', group: 'French (France)', accent: 'FR', gender: 'Female', flag: '🇫🇷', audio: 'fr-FR-VivienneDragonHDLatest-General-Audio-wav.wav' },
    { value: 'gu-IN-DhwaniNeural', label: 'Dhwani', group: 'Gujarati (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'gu-IN-NiranjanNeural', label: 'Niranjan', group: 'Gujarati (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'hi-IN-AaravNeural', label: 'Aarav', group: 'Hindi (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: 'hi-IN-Aarav-General-Audio-wav.wav' },
    { value: 'hi-IN-AnanyaNeural', label: 'Ananya', group: 'Hindi (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: 'hi-IN-Ananya-General-Audio-wav.wav' },
    { value: 'hi-IN-AartiNeural', label: 'Aarti', group: 'Hindi (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: 'hi-IN-Aarti-General-Audio-wav.wav' },
    { value: 'hi-IN-ArjunNeural', label: 'Arjun', group: 'Hindi (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: 'hi-IN-Arjun-General-Audio-wav.wav' },
    { value: 'hi-IN-KavyaNeural', label: 'Kavya', group: 'Hindi (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: 'hi-IN-Kavya-General-Audio-wav.wav' },
    { value: 'hi-IN-KunalNeural', label: 'Kunal', group: 'Hindi (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: 'hi-IN-Kunal-General-Audio-wav.wav' },
    { value: 'hi-IN-RehaanNeural', label: 'Rehaan', group: 'Hindi (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: 'hi-IN-Rehaan-General-Audio-wav.wav' },
    { value: 'hi-IN-SwaraNeural', label: 'Swara', group: 'Hindi (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: 'hi-IN-Swara-General-Audio-wav.wav' },
    { value: 'hi-IN-MadhurNeural', label: 'Madhur', group: 'Hindi (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: 'hi-IN-Madhur-General-Audio-wav.wav' },
    { value: 'it-IT-AlessioMultilingualNeural', label: 'Alessio', group: 'Italian (Italy)', accent: 'IT', gender: 'Male', flag: '🇮🇹', audio: 'it-IT-AlessioMultilingual-General-Audio-wav.wav' },
    { value: 'it-IT-IsabellaMultilingualNeural', label: 'Isabella', group: 'Italian (Italy)', accent: 'IT', gender: 'Female', flag: '🇮🇹', audio: 'it-IT-IsabellaMultilingual-General-Audio-wav.wav' },
    { value: 'it-IT-GiuseppeMultilingualNeural', label: 'Giuseppe', group: 'Italian (Italy)', accent: 'IT', gender: 'Male', flag: '🇮🇹', audio: 'it-IT-GiuseppeMultilingual-General-Audio-wav.wav' },
    { value: 'it-IT-MarcelloMultilingualNeural', label: 'Marcello', group: 'Italian (Italy)', accent: 'IT', gender: 'Male', flag: '🇮🇹', audio: 'it-IT-MarcelloMultilingual-General-Audio-wav.wav' },
    { value: 'ja-JP-Nanami:DragonHDLatestNeural', label: 'Nanami', group: 'Japanese (Japan)', accent: 'JP', gender: 'Female', flag: '🇯🇵', audio: 'ja-JP-NanamiDragonHDLatest-General-Audio-wav.wav' },
    { value: 'kn-IN-SapnaNeural', label: 'Sapna', group: 'Kannada (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'kn-IN-GaganNeural', label: 'Gagan', group: 'Kannada (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'ko-KR-HyunsuMultilingualNeural', label: 'Hyunsu', group: 'Korean (Korea)', accent: 'KR', gender: 'Male', flag: '🇰🇷', audio: 'ko-KR-HyunsuMultilingual-General-Audio-wav.wav' },
    { value: 'ml-IN-SobhanaNeural', label: 'Sobhana', group: 'Malayalam (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'ml-IN-MidhunNeural', label: 'Midhun', group: 'Malayalam (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'mr-IN-AarohiNeural', label: 'Aarohi', group: 'Marathi (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'mr-IN-ManoharNeural', label: 'Manohar', group: 'Marathi (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'ne-NP-HemkalaNeural', label: 'Hemkala', group: 'Nepali (Nepal)', accent: 'NP', gender: 'Female', flag: '🇳🇵', audio: '' },
    { value: 'ne-NP-SagarNeural', label: 'Sagar', group: 'Nepali (Nepal)', accent: 'NP', gender: 'Male', flag: '🇳🇵', audio: '' },
    { value: 'or-IN-SubhasiniNeural', label: 'Subhasini', group: 'Odia (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'or-IN-SukantNeural', label: 'Sukant', group: 'Odia (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'pa-IN-OjasNeural', label: 'Ojas', group: 'Punjabi (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'pa-IN-VaaniNeural', label: 'Vaani', group: 'Punjabi (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'pt-BR-MacerioMultilingualNeural', label: 'Macerio', group: 'Portuguese (Brazil)', accent: 'BR', gender: 'Male', flag: '🇧🇷', audio: 'pt-BR-MacerioMultilingual-General-Audio-wav.wav' },
    { value: 'pt-BR-ThalitaMultilingualNeural', label: 'Thalita', group: 'Portuguese (Brazil)', accent: 'BR', gender: 'Female', flag: '🇧🇷', audio: 'pt-BR-ThalitaMultilingual-General-Audio-wav.wav' },
    { value: 'ta-IN-PallaviNeural', label: 'Pallavi', group: 'Tamil (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'ta-IN-ValluvarNeural', label: 'Valluvar', group: 'Tamil (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'ta-LK-SaranyaNeural', label: 'Saranya', group: 'Tamil (Sri Lanka)', accent: 'LK', gender: 'Female', flag: '🇱🇰', audio: '' },
    { value: 'ta-LK-KumarNeural', label: 'Kumar', group: 'Tamil (Sri Lanka)', accent: 'LK', gender: 'Male', flag: '🇱🇰', audio: '' },
    { value: 'ta-MY-KaniNeural', label: 'Kani', group: 'Tamil (Malaysia)', accent: 'MY', gender: 'Female', flag: '🇲🇾', audio: '' },
    { value: 'ta-MY-SuryaNeural', label: 'Surya', group: 'Tamil (Malaysia)', accent: 'MY', gender: 'Male', flag: '🇲🇾', audio: '' },
    { value: 'ta-SG-VenbaNeural', label: 'Venba', group: 'Tamil (Singapore)', accent: 'SG', gender: 'Female', flag: '🇸🇬', audio: '' },
    { value: 'ta-SG-AnbuNeural', label: 'Anbu', group: 'Tamil (Singapore)', accent: 'SG', gender: 'Male', flag: '🇸🇬', audio: '' },
    { value: 'te-IN-ShrutiNeural', label: 'Shruti', group: 'Telugu (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'te-IN-MohanNeural', label: 'Mohan', group: 'Telugu (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'ur-IN-GulNeural', label: 'Gul', group: 'Urdu (India)', accent: 'IN', gender: 'Female', flag: '🇮🇳', audio: '' },
    { value: 'ur-IN-SalmanNeural', label: 'Salman', group: 'Urdu (India)', accent: 'IN', gender: 'Male', flag: '🇮🇳', audio: '' },
    { value: 'zh-CN-XiaochenMultilingualNeural', label: 'Xiaochen', group: 'Chinese (Mandarin, Simplified)', accent: 'CN', gender: 'Female', flag: '🇨🇳', audio: 'zh-CN-XiaochenMultilingual-General-Audio-wav.wav' },
    { value: 'zh-CN-XiaoxiaoMultilingualNeural', label: 'Xiaoxiao', group: 'Chinese (Mandarin, Simplified)', accent: 'CN', gender: 'Female', flag: '🇨🇳', audio: 'zh-CN-XiaoxiaoMultilingual-zhCN-Audio-wav.wav' },
    { value: 'zh-CN-XiaoyuMultilingualNeural', label: 'Xiaoyu', group: 'Chinese (Mandarin, Simplified)', accent: 'CN', gender: 'Female', flag: '🇨🇳', audio: 'zh-CN-XiaoyuMultilingual-General-Audio-wav.wav' },
    { value: 'zh-CN-YunyiMultilingualNeural', label: 'Yunyi', group: 'Chinese (Mandarin, Simplified)', accent: 'CN', gender: 'Male', flag: '🇨🇳', audio: 'zh-CN-YunyiMultilingual-General-Audio-wav.wav' },
    { value: 'zh-CN-YunxiaoMultilingualNeural', label: 'Yunxiao', group: 'Chinese (Mandarin, Simplified)', accent: 'CN', gender: 'Male', flag: '🇨🇳', audio: 'zh-CN-YunxiaoMultilingual-General-Audio-wav.wav' },
    { value: 'zh-CN-Xiaochen:DragonHDLatestNeural', label: 'Xiaochen', group: 'Chinese (Mandarin, Simplified)', accent: 'CN', gender: 'Female', flag: '🇨🇳', audio: 'zh-CN-XiaochenDragonHDLatest-General-Audio-wav.wav' },
    { value: 'zh-CN-Yunfan:DragonHDLatestNeural', label: 'Yunfan', group: 'Chinese (Mandarin, Simplified)', accent: 'CN', gender: 'Male', flag: '🇨🇳', audio: 'zh-CN-YunfanDragonHDLatest-General-Audio-wav.wav' },
];
