# Generated by Django 5.2.15 on 2026-07-01 20:06

import django.db.models.deletion
import projects.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled demo', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('rendering', 'Rendering'), ('ready', 'Ready')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=20)),
                ('share_slug', models.SlugField(default=projects.models.generate_share_slug, editable=False, max_length=16, unique=True)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='')),
                ('duration', models.FloatField(default=0, help_text='Rendered duration (seconds)')),
                ('aspect_ratio', models.CharField(default='16:9', max_length=12)),
                ('language', models.CharField(default='en', max_length=12)),
                ('recording_data', models.JSONField(blank=True, default=dict, help_text='Captured events (clicks, moves), viewport, cursor data')),
                ('edit_data', models.JSONField(blank=True, default=dict, help_text='Editor state: color grading, text overlays, camera, effects')),
                ('script_segments', models.JSONField(blank=True, default=list, help_text='Array of {text, timestamp} narration segments')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='projects_pr_owner_i_242348_idx'), models.Index(fields=['share_slug'], name='projects_pr_share_s_1af095_idx')],
            },
        ),
    ]
