from decimal import Decimal

# This is your MASTER PRICING CONTROL PANEL

# 1. Platform Fee: A fixed cost for every generation.
PLATFORM_FEE = Decimal('0.5')

# 2. Default Multiplier: A fallback for any voice not listed below.
DEFAULT_VOICE_MULTIPLIER = Decimal('1.5')

# 3. Per-Voice Multipliers: The heart of your pricing.
# Edit the multiplier for any voice here to instantly change its price.
VOICE_MULTIPLIERS = {
    # --- ✨ Free Promotional Voices (0.0x) ---
    'en-US-JennyNeural': Decimal('0.0'),
    'hi-IN-SwaraNeural': Decimal('0.0'),

    # --- 🇮🇳 Local Pro Voices (1.0x) ---
    'bn-BD-NabanitaNeural': Decimal('1.0'),
    'bn-BD-PradeepNeural': Decimal('1.0'),
    'bn-IN-TanishaaNeural': Decimal('1.0'),
    'bn-IN-BashkarNeural': Decimal('1.0'),
    'en-IN-AaravNeural': Decimal('1.0'),
    'en-IN-AashiNeural': Decimal('1.0'),
    'en-IN-AartiNeural': Decimal('1.0'),
    'en-IN-ArjunNeural': Decimal('1.0'),
    'en-IN-AnanyaNeural': Decimal('1.0'),
    'en-IN-KavyaNeural': Decimal('1.0'),
    'en-IN-KunalNeural': Decimal('1.0'),
    'en-IN-NeerjaNeural': Decimal('1.0'),
    'en-IN-PrabhatNeural': Decimal('1.0'),
    'en-IN-RehaanNeural': Decimal('1.0'),
    'en-IN-AartiIndicNeural': Decimal('1.0'),
    'en-IN-ArjunIndicNeural': Decimal('1.0'),
    'en-IN-NeerjaIndicNeural': Decimal('1.0'),
    'en-IN-PrabhatIndicNeural': Decimal('1.0'),
    'gu-IN-DhwaniNeural': Decimal('1.0'),
    'gu-IN-NiranjanNeural': Decimal('1.0'),
    'hi-IN-AaravNeural': Decimal('1.0'),
    'hi-IN-AnanyaNeural': Decimal('1.0'),
    'hi-IN-AartiNeural': Decimal('1.0'),
    'hi-IN-ArjunNeural': Decimal('1.0'),
    'hi-IN-KavyaNeural': Decimal('1.0'),
    'hi-IN-KunalNeural': Decimal('1.0'),
    'hi-IN-RehaanNeural': Decimal('1.0'),
    'hi-IN-MadhurNeural': Decimal('1.0'),
    'kn-IN-SapnaNeural': Decimal('1.0'),
    'kn-IN-GaganNeural': Decimal('1.0'),
    'ml-IN-SobhanaNeural': Decimal('1.0'),
    'ml-IN-MidhunNeural': Decimal('1.0'),
    'mr-IN-AarohiNeural': Decimal('1.0'),
    'mr-IN-ManoharNeural': Decimal('1.0'),
    'ne-NP-HemkalaNeural': Decimal('1.0'),
    'ne-NP-SagarNeural': Decimal('1.0'),
    'or-IN-SubhasiniNeural': Decimal('1.0'),
    'or-IN-SukantNeural': Decimal('1.0'),
    'pa-IN-OjasNeural': Decimal('1.0'),
    'pa-IN-VaaniNeural': Decimal('1.0'),
    'ta-IN-PallaviNeural': Decimal('1.0'),
    'ta-IN-ValluvarNeural': Decimal('1.0'),
    'ta-LK-SaranyaNeural': Decimal('1.0'),
    'ta-LK-KumarNeural': Decimal('1.0'),
    'ta-MY-KaniNeural': Decimal('1.0'),
    'ta-MY-SuryaNeural': Decimal('1.0'),
    'ta-SG-VenbaNeural': Decimal('1.0'),
    'ta-SG-AnbuNeural': Decimal('1.0'),
    'te-IN-ShrutiNeural': Decimal('1.0'),
    'te-IN-MohanNeural': Decimal('1.0'),
    'ur-IN-GulNeural': Decimal('1.0'),
    'ur-IN-SalmanNeural': Decimal('1.0'),

    # --- 🌍 Global Standard Voices (1.5x) ---
    'en-KE-AsiliaNeural': Decimal('1.5'),
    'en-KE-ChilembaNeural': Decimal('1.5'),
    'en-NG-EzinneNeural': Decimal('1.5'),
    'en-NG-AbeoNeural': Decimal('1.5'),
    'en-NZ-MollyNeural': Decimal('1.5'),
    'en-NZ-MitchellNeural': Decimal('1.5'),
    'en-PH-RosaNeural': Decimal('1.5'),
    'en-PH-JamesNeural': Decimal('1.5'),
    'en-SG-LunaNeural': Decimal('1.5'),
    'en-SG-WayneNeural': Decimal('1.5'),
    'en-TZ-ImaniNeural': Decimal('1.5'),
    'en-TZ-ElimuNeural': Decimal('1.5'),
    'en-US-AvaNeural': Decimal('1.5'),
    'en-US-AndrewNeural': Decimal('1.5'),
    'en-US-EmmaNeural': Decimal('1.5'),
    'en-US-BrianNeural': Decimal('1.5'),
    'en-US-GuyNeural': Decimal('1.5'),
    'en-US-AriaNeural': Decimal('1.5'),
    'en-US-DavisNeural': Decimal('1.5'),
    'en-US-JaneNeural': Decimal('1.5'),
    'en-US-JasonNeural': Decimal('1.5'),
    'en-US-KaiNeural': Decimal('1.5'),
    'en-US-LunaNeural': Decimal('1.5'),
    'en-US-SaraNeural': Decimal('1.5'),
    'en-US-TonyNeural': Decimal('1.5'),
    'en-US-NancyNeural': Decimal('1.5'),
    'en-US-AmberNeural': Decimal('1.5'),
    'en-US-AnaNeural': Decimal('1.5'),
    'en-US-AshleyNeural': Decimal('1.5'),
    'en-US-BrandonNeural': Decimal('1.5'),
    'en-US-ChristopherNeural': Decimal('1.5'),
    'en-US-CoraNeural': Decimal('1.5'),
    'en-US-ElizabethNeural': Decimal('1.5'),
    'en-US-EricNeural': Decimal('1.5'),
    'en-US-JacobNeural': Decimal('1.5'),
    'en-US-MichelleNeural': Decimal('1.5'),
    'en-US-MonicaNeural': Decimal('1.5'),
    'en-US-RogerNeural': Decimal('1.5'),
    'en-US-SteffanNeural': Decimal('1.5'),
    'en-US-BlueNeural': Decimal('1.5'),
    'en-ZA-LeahNeural': Decimal('1.5'),
    'en-ZA-LukeNeural': Decimal('1.5'),

    # --- 💎 Premium AI Voices (2.5x) ---
    'de-DE-FlorianMultilingualNeural': Decimal('2.5'),
    'en-GB-AdaMultilingualNeural': Decimal('2.5'),
    'en-GB-OllieMultilingualNeural': Decimal('2.5'),
    'en-US-AvaMultilingualNeural': Decimal('2.5'),
    'en-US-AndrewMultilingualNeural': Decimal('2.5'),
    'en-US-EmmaMultilingualNeural': Decimal('2.5'),
    'en-US-BrianMultilingualNeural': Decimal('2.5'),
    'en-US-CoraMultilingualNeural': Decimal('2.5'),
    'en-US-ChristopherMultilingualNeural': Decimal('2.5'),
    'en-US-BrandonMultilingualNeural': Decimal('2.5'),
    'en-US-JennyMultilingualNeural': Decimal('2.5'),
    'en-US-RyanMultilingualNeural': Decimal('2.5'),
    'en-US-AdamMultilingualNeural': Decimal('2.5'),
    'en-US-AmandaMultilingualNeural': Decimal('2.5'),
    'en-US-DavisMultilingualNeural': Decimal('2.5'),
    'en-US-DerekMultilingualNeural': Decimal('2.5'),
    'en-US-DustinMultilingualNeural': Decimal('2.5'),
    'en-US-EvelynMultilingualNeural': Decimal('2.5'),
    'en-US-LewisMultilingualNeural': Decimal('2.5'),
    'en-US-LolaMultilingualNeural': Decimal('2.5'),
    'en-US-NancyMultilingualNeural': Decimal('2.5'),
    'en-US-PhoebeMultilingualNeural': Decimal('2.5'),
    'en-US-SamuelMultilingualNeural': Decimal('2.5'),
    'en-US-SerenaMultilingualNeural': Decimal('2.5'),
    'en-US-SteffanMultilingualNeural': Decimal('2.5'),
    'es-ES-ArabellaMultilingualNeural': Decimal('2.5'),
    'es-ES-IsidoraMultilingualNeural': Decimal('2.5'),
    'es-ES-TristanMultilingualNeural': Decimal('2.5'),
    'es-ES-XimenaMultilingualNeural': Decimal('2.5'),
    'fr-FR-VivienneMultilingualNeural': Decimal('2.5'),
    'fr-FR-RemyMultilingualNeural': Decimal('2.5'),
    'fr-FR-LucienMultilingualNeural': Decimal('2.5'),
    'it-IT-AlessioMultilingualNeural': Decimal('2.5'),
    'it-IT-IsabellaMultilingualNeural': Decimal('2.5'),
    'it-IT-GiuseppeMultilingualNeural': Decimal('2.5'),
    'it-IT-MarcelloMultilingualNeural': Decimal('2.5'),
    'ko-KR-HyunsuMultilingualNeural': Decimal('2.5'),
    'pt-BR-MacerioMultilingualNeural': Decimal('2.5'),
    'pt-BR-ThalitaMultilingualNeural': Decimal('2.5'),
    'zh-CN-XiaochenMultilingualNeural': Decimal('2.5'),
    'zh-CN-XiaoxiaoMultilingualNeural': Decimal('2.5'),
    'zh-CN-XiaoyuMultilingualNeural': Decimal('2.5'),
    'zh-CN-YunyiMultilingualNeural': Decimal('2.5'),
    'zh-CN-YunxiaoMultilingualNeural': Decimal('2.5'),

    # --- 🔥 Ultra HD & Turbo Voices (4.0x) ---
    'de-DE-Florian:DragonHDLatestNeural': Decimal('4.0'),
    'de-DE-Seraphina:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-AlloyTurboMultilingualNeural': Decimal('4.0'),
    'en-US-EchoTurboMultilingualNeural': Decimal('4.0'),
    'en-US-FableTurboMultilingualNeural': Decimal('4.0'),
    'en-US-OnyxTurboMultilingualNeural': Decimal('4.0'),
    'en-US-NovaTurboMultilingualNeural': Decimal('4.0'),
    'en-US-ShimmerTurboMultilingualNeural': Decimal('4.0'),
    'en-US-AshTurboMultilingualNeural': Decimal('4.0'),
    'en-US-AIGenerate1Neural': Decimal('4.0'),
    'en-US-AIGenerate2Neural': Decimal('4.0'),
    'en-US-Adam:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Andrew:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Andrew2:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Ava:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Brian:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Davis:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Emma:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Emma2:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Steffan:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Alloy:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Andrew3:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Aria:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Ava3:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Bree:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Jenny:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-MultiTalker-Ava-Andrew:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-MultiTalker-Ava-Steffan:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Nova:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Phoebe:DragonHDLatestNeural': Decimal('4.0'),
    'en-US-Serena:DragonHDLatestNeural': Decimal('4.0'),
    'es-ES-Tristan:DragonHDLatestNeural': Decimal('4.0'),
    'es-ES-Ximena:DragonHDLatestNeural': Decimal('4.0'),
    'fr-FR-Remy:DragonHDLatestNeural': Decimal('4.0'),
    'fr-FR-Vivienne:DragonHDLatestNeural': Decimal('4.0'),
    'ja-JP-Nanami:DragonHDLatestNeural': Decimal('4.0'),
    'zh-CN-Xiaochen:DragonHDLatestNeural': Decimal('4.0'),
    'zh-CN-Yunfan:DragonHDLatestNeural': Decimal('4.0'),
}
